---
title: "Econometrics II Notes 20201"
author: "James Bland"
date: "Spring 2021"
output:
  bookdown::gitbook: default
---

```{r setup, include=FALSE}
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message=FALSE,cache=TRUE)
```

# Limited dependent variable models

## Some example data

```{r loadTirtanic}
library(dplyr)
D<-(data.frame(read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/carData/TitanicSurvival.csv"))
)

DSummary<-D %>% group_by(sex,age,passengerClass) %>% summarize(fracSurvived = mean(1*(survived=="yes")),n=n())

knitr::kable(head(DSummary))
```

```{r PlotTitanic,cache=T}
library(ggplot2)
(ggplot(DSummary ,aes(y=fracSurvived,x=age,color=sex,shape=passengerClass,size=n))
  +geom_point()
 +theme_bw()
  +xlab("Age")
  +ylab("Fraction survived")
  +theme_bw()
)
```

## Analyzing with linear regression

```{r linreg, results="asis"}

D <- (D
  %>% mutate(adult = 1*(age>=18),
             class2 = 1*(passengerClass=="2nd"),
             class3 = 1*(passengerClass=="3rd"),
             male = 1*(sex=="male"),
             S = 1*(survived=="yes")
             )
)

reg1<-lm(S ~ age + male+class2+class3,data=D)
reg2<-lm(S ~ age + adult+ male+class2+class3,data=D)
reg3<-lm(S ~ age + adult +adult*male + male + class2 + class3,data=D)


library(stargazer)
stargazer(reg1,reg2,reg3,type="html")

```

```{r PlotTitanicLinear,cache=T}

(ggplot(DSummary ,aes(y=fracSurvived,x=age,color=sex,shape=passengerClass,size=n))
  +geom_smooth(method="lm")
  +geom_point()
 +theme_bw()
  +xlab("Age")
  +ylab("Fraction survived")
  +theme_bw()
)
```

## Focusing on males only

```{r TitanicMale}

(
  ggplot(data=(D %>% filter(sex=="male")), aes(x=age,y=1*(survived=="yes"),group=paste(factor(age<18),passengerClass),color=passengerClass))
  +geom_smooth(method="lm",formula = y~ x + (1*(x<18)))
  +geom_point(data=(DSummary %>% filter(sex=="male")) ,aes(y=fracSurvived,x=age,color=passengerClass,size=n))
  
  +theme_bw()
  +labs(title="Titanic survival (males only)")
)

```

```{r,results="asis"}
Dmale<-(D%>%filter(sex=="male")
         %>% mutate(AgeMinus18 = age-18)
)

reg1<-lm(S ~ AgeMinus18 + class2+class3,data=Dmale)
reg2<-lm(S ~ AgeMinus18 + adult+class2+class3,data=Dmale)
reg3<-lm(S ~ AgeMinus18 + adult +AgeMinus18*adult+ class2 + class3,data=Dmale)

stargazer(reg1,reg2,reg3,type="html")
fitted<-(reg3$fitted.values)
(
  ggplot(data=data.frame(fitted),aes(x=fitted))
  +geom_histogram(bins=20)
  +theme_bw()
  +geom_vline(xintercept=0)
)

```

```{r,results="asis"}
probit1<-glm(S ~ AgeMinus18 + class2+class3,data=Dmale,family=binomial(link="probit"))
probit2<-glm(S ~ AgeMinus18+adult*(AgeMinus18) + adult+ class2+class3,data=Dmale,family=binomial(link="probit"))

stargazer(probit1,probit2,type="html")
```

